os:
  - linux
language: nix
sudo: required
before_install:
  - sudo mkdir -p /etc/nix
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use cachix
  - cachix use dapp
  - git clone --recursive https://github.com/dapphub/dapptools $HOME/.dapp/dapptools
  - nix-env -f $HOME/.dapp/dapptools -iA dapp solc
script:
  - dapp --use solc:0.5.12 test
