os:
  - linux
language: nix
sudo: required
before_install:
  - sudo mkdir -p /etc/nix
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use cachix
  - cachix use dapp
  - nix-env -f https://github.com/dapphub/dapptools/tarball/master -iA dapp
script:
  - dapp --use solc:0.5.11 test
